server:
  port: 9900
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 30000
  servlet:
    context-path: /xinan
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://1.14.135.139:30000/xinan-db
#    url: jdbc:postgresql://1.14.135.139:30000/new-xinandb
    url: jdbc:postgresql://localhost:5432/xinan-db
    username: xinandb
    password: xinandb@pg2021#!
    hikari:
      maximum-pool-size: 3
      max-lifetime: 1800000
      connection-timeout: 30000
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=1000,expireAfterWrite=120s
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/static/html/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations:
    - classpath*:/mapper/*.xml

yzmeta:
  debug: false
  login-count: 3
  allow-file-type: xlsx|xls|pdf|png|jpeg|jpg|gif|mp4|doc|docx
  upload-dir: D:/temp/upload
  default-passwd: xinan1234

